version: "3.2"

services:
  db:
    image: apache/hop-web:latest
    ports:
      - "8080:8080"
    environment:
      HOP_PROJECT_FOLDER: /
      HOP_PROJECT_NAME: bdm-delitos-caba
      HOP_ENVIRONMENT_NAME: bdm-delitos-caba
    volumes:
      - "./:/project"
